eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/      # ×¢²áServerµØÖ·
    register-with-eureka: false                       # ×¢²áServer±ÜÃâ×÷Îª×¢²áClientÔÙ´Î×¢²á

spring:
  application:
    name: eureka

server:
  port: 8761