eureka:
  client:
    service-url:
      defaultZone: http://eureka2:8762/eureka/  # 注册Server地址，高可用模式下Eureka Server之间相互环形注册
    #register-with-eureka: false  # 禁止自己作为服务进行注册，高可用（注册中心集群）时必须打开进行相互注册，不然副本无法可用
  instance:
    hostname: eureka1   # 自定义服务实例HostName
  server:
    enable-self-preservation: false  # 心跳检查Client服务的上线率，对于上线率低的机器会认为实例在线（自我保护模式），开发环境可以关闭保护

spring:
  application:
    name: eureka

server:
  port: 8761