eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/    #注册中心地址
  instance:
    hostname: eurekaClent                           #自定义服务实例HostName

spring:
  application:
    name: eureka_client